-- http://www.ravi.io/buzzfeed-title-generator

local utils = require("irc.utils")

local buzzfeed_words = {
	people = {
		"Architects",
		"Cats",
		"Video Game Characters",
		"Advertising Executives",
		"Teachers",
		"Doctors",
		"Nurse Practictioners",
		"Bodybuilders",
		"NFL Linebackers",
		"World Leaders",
		"Swimmers",
		"Wolves",
		"Sentient Humanoids",
		"Muggles",
		"Whales",
		"Comedians",
		"NBA Players",
		"Background Actors",
		"Celebrities",
		"People",
		"'90s Kids",
		"Music Stars",
		"Tattoo Artists",
		"Oscar Winners",
		"Snapchat Billionaires",
		"Members of Limp Bizkit",
		"Avril Lavigne Fans",
		"Male Models",
		"Card Sharks",
		"Miners",
		"Investigative Journalists",
		"Smurfs",
		"Wimbledon Ballboys",
		"Aziz Ansari Impersonators",
		"People With Jetlag",
		"Parents",
		"Diplomats",
		"Atlanta Falcons",
		"Cowboys",
		"Justin Timberlake Fans",
		"Lazy People",
		"Commentators",
		"News Anchors",
		"Olympic Medalists",
		"Superheroes",
		"Comic Book Villains",
		"Real Estate Moguls",
		"Disney Princesses",
		"Mad Men Characters",
		"Game of Thrones Characters",
		"Celebrity Impersonators",
		"Kardashians",
		"Deal or No Deal Models",
		"Cover Bands",
		"Former SNL Castmembers"
	},
	adjest = {
		"Best",
		"Coolest",
		"Cutest",
		"Creepiest",
		"Worst",
		"Greatest",
		"Cheesiest",
		"Funniest",
		"Illest",
		"Ghastliest",
		"Biggest",
		"Slowest",
		"Most Delicate",
		"Most Picturesque",
		"Most Arrogant",
		"Most Confusing",
		"Most Beautiful",
		"Most Courageous",
		"Most Successful",
		"Most Tasteless",
		"Most Jizz-Worthy",
		"Most Inspirational",
		"Most Important",
		"Most Awkward",
		"Most Disturbing",
		"Most Popular",
		"Most Beloved",
		"Most Wanted",
		"Most Adorable",
		"Most Unbelievably Flawless And Life-Changing"
	},
	time = {
		"All Time",
		"Your Childhood",
		"2013",
		"The Last 10 Years",
		"The '80s",
		"Last Summer",
		"This Holday Season",
		"The '90s",
		"This Year",
		"This Century",
		"The Post-Y2K Era"
	},
	noun = {
		"Halloween Costumes",
		"Christmas Stock Photos",
		"Gifts",
		"Costumes",
		"Charts",
		"Emojis",
		"Facts",
		"Gowns",
		"GIFs",
		"Things",
		"Horses",
		"Items Of Clothing",
		"Moments",
		"Photographs",
		"Pictures",
		"Potatoes",
		"Pug Puppies",
		"Puns",
		"Ways To Eat A Burrito",
		"Easter Eggs",
		"Stories",
		"Things",
		"Truths",
		"Salads",
		"Cars",
		"Water Bottles",
		"Computer Mouses",
		"Punctuation Marks",
		"Christmas Foods",
		"Snapchat Filters",
		"Husky Puppies",
		"Series Finales",
		"Movie Scenes",
		"Country Songs",
		"Tweets",
		"VH1 Specials",
		"Investment Bankers",
		"SAT Words",
		"Autocorrects",
		"Memes",
		"Instagrams",
		"Snapchats",
		"Wedding Rings",
		"Fragrances",
		"Optical Illusions",
		"Advertisements",
		"Vegetables",
		"Animals",
		"Minerals",
		"Cheeses",
		"iPhone Apps",
		"Frat Houses",
		"Oprah-Grams",
		"Corporations",
		"Government Departments",
		"Doge Memes",
		"Pastries",
		"HBO Shows"
	},
	prep = {
		"From Beyoncé's New Album",
		"In The World",
		"In America",
		"From Christmas Songs",
		"From \"The Lion King\"",
		"From \"Forrest Gump\"",
		"From The Ocean Floor",
		"In South America",
		"In A Burrito",
		"In Space",
		"On Mars",
		"From \"The Avengers\"",
		"From LOST",
		"From Breaking Bad",
		"From Around The World",
		"From \"Home Alone\"",
		"From National Geographic's History",
		"From Last Night's \"Saturday Night Live\"",
		"From Politicians in 2013",
		"From Webcomics",
		"From Britney Spears' Upcoming Documentary",
		"On The Moon",
		"From the National Hockey League",
		"From \"The Daily Show\"",
		"From Congress",
		"From One Direction Songs",
		"From \"Duck Dynasty\"",
		"From The \"Doctor Who\" 50th Anniversary",
		"In The History Of Cute",
		"In Ryan Gosling's 33 Years On Earth",
		"From The NYC Marathon"
	},
	noun_desc = {
		"'00s Teens Will Never Wear Again",
		"2000s Teens Loved",
		"Are Way More Important Than Work Right Now",
		"Every Twentysomething Needs",
		"Look Like Channing Tatum",
		"Look Like Miley Cyrus",
		"Never Stop Being Awkward",
		"Only Eldest Siblings Know",
		"Prove Cats Have Hearts Of Gold",
		"Prove Pugs Always Win At Halloween",
		"Prove The World Isn't Such A Bad Place",
		"Prove You And Your Mother Are The Same Person",
		"Scream World Domination",
		"Should Be Illegal",
		"Should Exist But Don't",
		"Will Haunt Your Dreams",
		"Will Help You Get Through The Week",
		"Will Make You Feel Filthy",
		"Will Make You Laugh Every Time",
		"Will Make You Want To Fall In Love",
		"Will Make Your Skin Crawl",
		"Will Restore Your Faith In The Internet",
		"You'll Want To Keep For Yourself"
	},
	people_desc = {
		"Are Too Clever For Their Own Good",
		"Completely Screwed Up Their One Job",
		"Had A Worse Year Than You",
		"Have No Idea What They Are Doing",
		"Are Only Famous To People Who Live In New York",
		"Are Having A Really Rough Day",
		"Need To Be Banned From Celebrating Halloween",
		"Tried To Find An Original Way To Go As Miley Cyrus For Halloween",
		"Are Clearly Being Raised Right",
		"Have Performed For Dictators",
		"Will Make You Feel Like A Genius",
		"Absolutely Nailed It In 2013"
	},
	num = {
		10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50
	}
}

local formulas = {
    {'num', {'Painful Truths', 'Problems', 'Things'}, 'Only', 'people', 'Will Understand'},
    {'The', 'num', 'adjest', 'noun', 'Of', 'time'},
    {'The', 'num', 'adjest', 'noun', 'prep'},
    {{'The', ''}, 'num', 'noun', 'That', 'noun_desc'},
    {'num', 'people', 'Who', 'people_desc'}
}

return function()
	local words = utils.deepcopy(buzzfeed_words)
	local formula = utils.random_choice(formulas)
	local ret = {}
	for _, word in ipairs(formula) do
		if type(word) == "table" then
			word = utils.random_choice(word)
		end
		if words[word] then
			table.insert(ret, table.remove(words[word], math.random(#words[word])))
		else
			table.insert(ret, word)
		end
	end
	return utils.strip(table.concat(ret, " "))
end